/**
 * Read-only event catalog for pluginApi.events.
 *
 * The catalog is the source of truth for typed subscriptions: event name,

 * official dispatch mode, scope-filtered status, scope-key resolution, payload
 * shape, source feature id, A/B provenance, and the per-event fault/freeze
 * policies used by the event bus.
 *
 * First version covered exactly the 19 in-scope event names of
 * plugin-api-events-m1. plugin-api-agent-m1 extends it with the 12 official
 * `agent/*` events (31 total).
 *
 * The catalog is deeply frozen and must never be mutated at runtime.
 */

function deepFreeze(value) {
  if (value === null || typeof value !== 'object') return value
  for (const key of Object.keys(value)) deepFreeze(value[key])
  return Object.freeze(value)
}

const A = 'A'
const CONTAIN = 'contain'
const FREEZE_ALL = 'all'

/**
 * @type {Array<{
 *   name: string,
 *   mode: 'on' | 'emit' | 'serial' | 'parallel' | 'bail' | 'waterfall',
 *   scopeFiltered: boolean,
 *   scopeKey: 'args[0].agent' | 'args[1].scope' | null | undefined,
 *   payload: string,
 *   args: string,
 *   source: string,
 *   type: 'A' | 'B',
 *   fault: 'contain' | 'created' | 'propagate',
 *   freeze: 'all' | { deep: string[] },
 *   feature?: string,
 * }>}
 */
const entries = [
  // -- plugin-api-events-m1 (19 events) --
  {
    name: 'fs/write-intent',
    mode: 'waterfall',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: 'logical payload {target, exec}; target = {targetKey, displayPath}',
    args: '(target, exec, next)',
    source: 'O1',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'fs/edit-intent',
    mode: 'waterfall',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: 'logical payload {target, exec}; target = {targetKey, displayPath}',
    args: '(target, exec, next)',
    source: 'O2',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'fs/observed',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: "logical payload {target, observation, actor}; observation.kind: 'present' | 'absent'",
    args: '(target, observation, actor)',
    source: 'O3',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'subagent/start',
    mode: 'emit',
    scopeFiltered: true,
    scopeKey: null, // presence-only: scope key comes from the dispatch carrier, not from args
    payload: '{runId, provider, id, local}',
    args: '(info)',
    source: 'O4',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'subagent/end',
    mode: 'emit',
    scopeFiltered: true,
    scopeKey: null,
    payload: '{runId, provider, id, local, stopReason, lastAssistantMessage?}',
    args: '(info)',
    source: 'O4',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'subagent/provider-added',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: 'provider',
    args: '(provider)',
    source: 'O5',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'subagent/provider-removed',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: 'providerName',
    args: '(providerName)',
    source: 'O5',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'workflow/start',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: 'info {id, meta}',
    args: '(info)',
    source: 'O6',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'workflow/phase',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: '(info, title)',
    args: '(info, title)',
    source: 'O6',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'workflow/log',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: '(info, message)',
    args: '(info, message)',
    source: 'O6',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'workflow/agent-start',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: '(info, agent)',
    args: '(info, agent)',
    source: 'O6',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'workflow/agent-end',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: '(info, agent)',
    args: '(info, agent)',
    source: 'O6',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'workflow/end',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: '(info, {stopReason, error?, agentsStarted})',
    args: '(info, settled)',
    source: 'O6',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'approval/request',
    mode: 'waterfall',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: "req {agent, toolName, callId?, reason?, signal}; outcome 'allowed-once' | 'rejected' | 'cancelled' | 'unavailable'",
    args: '(req, next)',
    source: 'O7',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'commands/change',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: 'none',
    args: '()',
    source: 'O9',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'skills/change',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: 'none',
    args: '()',
    source: 'O10',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'credentials/updated',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: 'ref',
    args: '(ref)',
    source: 'O11',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'goal/changed',
    mode: 'emit',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{agent, change}',
    args: '(payload)',
    source: 'O12',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  {
    name: 'session-telemetry/record',
    mode: 'waterfall',
    scopeFiltered: false,
    scopeKey: undefined,
    payload: 'logical payload {record}',
    args: '(record, next)',
    source: 'O16',
    type: A,
    fault: CONTAIN,
    freeze: FREEZE_ALL,
  },
  // -- plugin-api-agent-m1 (12 agent/* events) --
  {
    name: 'agent/created',
    mode: 'emit',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{ agent }',
    args: '(payload)',
    source: 'A1',
    type: A,
    fault: 'created', // official: sync throw vetoes publication, async rejection is reported
    freeze: { deep: [] },
  },
  {
    name: 'agent/disposed',
    mode: 'emit',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{ agent }',
    args: '(payload)',
    source: 'A1',
    type: A,
    fault: CONTAIN,
    freeze: { deep: [] },
  },
  {
    name: 'agent/status',
    mode: 'emit',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{ agent, status }',
    args: '(payload)',
    source: 'A1',
    type: A,
    fault: CONTAIN,
    freeze: { deep: [] },
  },
  {
    name: 'agent/session-start',
    mode: 'emit',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{ agent, source }',
    args: '(payload)',
    source: 'A1',
    type: A,
    fault: CONTAIN,
    freeze: { deep: [] },
  },
  {
    name: 'agent/inbox/inserted',
    mode: 'emit',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{ agent, message }',
    args: '(payload)',
    source: 'A2',
    type: A,
    fault: CONTAIN,
    freeze: { deep: [] },
  },
  {
    name: 'agent/inbox/claimed',
    mode: 'emit',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{ agent, message, turn }',
    args: '(payload)',
    source: 'A2',
    type: A,
    fault: CONTAIN,
    freeze: { deep: [] },
  },
  {
    name: 'agent/inbox/discarded',
    mode: 'emit',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{ agent, message }',
    args: '(payload)',
    source: 'A2',
    type: A,
    fault: CONTAIN,
    freeze: { deep: [] },
  },
  {
    name: 'agent/pre-step',
    mode: 'waterfall',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{ agent, messages, turn, step, signal }',
    args: '(payload, next)',
    source: 'A3',
    type: A,
    fault: 'propagate',
    freeze: { deep: ['messages'] },
  },
  {
    name: 'agent/request',
    mode: 'waterfall',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{ agent, turn, step, signal }',
    args: '(payload, next)',
    source: 'A4',
    type: A,
    fault: 'propagate',
    freeze: { deep: [] },
  },
  {
    name: 'agent/request-error',
    mode: 'waterfall',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{ agent, turn, step, provider, failure, retryPolicy, signal }',
    args: '(payload, next)',
    source: 'A5',
    type: A,
    fault: 'propagate',
    freeze: { deep: ['failure'] },
  },
  {
    name: 'agent/turn-stopping',
    mode: 'serial',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{ agent, turn, signal }',
    args: '(payload)',
    source: 'A6',
    type: A,
    fault: 'propagate',
    freeze: { deep: [] },
  },
  {
    name: 'agent/error',
    mode: 'emit',
    scopeFiltered: true,
    scopeKey: 'args[0].agent',
    payload: '{ agent, turn, step, error }',
    args: '(payload)',
    source: 'A7',
    type: A,
    fault: CONTAIN,
    freeze: { deep: [] },
  },
  {
    name: 'llm/stream',
    mode: 'waterfall',
    scopeFiltered: false,
    scopeKey: undefined,
    fault: 'contain',
    freeze: 'all',
    payload: 'GenerateOptions (official dsh-llm type); this binding is the LlmRuntime; next(): AsyncIterable<StreamChunk>',
    args: '(options, next)',
    source: 'L3',
    type: A,
  },
  {
    name: 'llm/adapters-updated',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    fault: 'contain',
    freeze: 'all',
    payload: 'none',
    args: '()',
    source: 'L6',
    type: A,
  },
  {
    name: 'system-prompt/assemble',
    mode: 'waterfall',
    scopeFiltered: true,
    scopeKey: 'args[1].scope',
    fault: 'contain',
    freeze: 'all',
    payload: 'assembly {sections, contexts, tools, variables}; context {scope?, signal?}',
    args: '(assembly, context, next)',
    source: 'P6',
    type: A,
  },
  {
    name: 'system-prompt/change',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    fault: 'contain',
    freeze: 'all',
    payload: 'none',
    args: '()',
    source: 'P7',
    type: A,
  },
  {
    name: 'settings/updated',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    fault: 'contain',
    freeze: 'all',
    payload: "ns: SettingsNamespace; next/prev: resolved values; source: 'update' | 'provider'",
    args: '(ns, next, prev, source)',
    source: 'ST3',
    type: A,
    feature: 'settings',
  },
  {
    name: 'settings/document-updated',
    mode: 'emit',
    scopeFiltered: false,
    scopeKey: undefined,
    fault: 'contain',
    freeze: 'all',
    payload: 'ns: SettingsNamespace; revision: number',
    args: '(ns, revision)',
    source: 'ST3',
    type: A,
    feature: 'settings',
  },
]

/** @type {Readonly<Record<string, typeof entries[number]>>} */
export const eventsCatalog = deepFreeze(Object.fromEntries(entries.map((entry) => [entry.name, entry])))

/**
 * @param {string} name - event name
 * @returns {typeof entries[number] | undefined} the frozen catalog entry, if cataloged
 */
export function catalogEntryOf(name) {
  return eventsCatalog[name]
}

/**
 * Shallow-merge several catalogs into one deeply-frozen catalog.
 *
 * Used by the host apply to extend `pluginApi.events.catalog` with the six
 * `tools/*` entries when the `tools` feature is active. The base catalogs are
 * not mutated. Any failure degrades to the base `eventsCatalog` so catalog
 * construction can never take down the event bus.
 *
 * @param {...Record<string, object>} catalogs - catalogs to merge, later keys win
 * @returns {Readonly<Record<string, object>>} merged deeply-frozen catalog
 */
export function mergeEventCatalogs(...catalogs) {
  try {
    return deepFreeze(Object.assign({}, ...catalogs))
  } catch {
    return eventsCatalog
  }
}
